name: Build And Deploy CSS

on:
  workflow_call:
  
jobs:
  build-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get node_modules From Cache
        id: get-modules
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}/node_modules
          key: node-modules
          restore-keys: node-modules-
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Load Dependency
        run: npm ci
      - name: Build CSS
        run: npm run build; npm run build:web
      - name: Generate changelogs
        run: npm run changelog; mv CHANGELOG.md css/
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy to release branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release
          folder: css
          clean: true