name: Release

on:
  push:
    branches: [main]
    paths:
      - 'scss/*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-css.yml

  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release-package.yml

