name: Release Packages

on:
  workflow_call:

env:
  THEME_NAME: "logseq-developer-theme"
  FONTS_PATH: "~/fonts"

jobs:

  merge-dev-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout theme files
        uses: actions/checkout@v3
        with:
           ref: release
           fetch-depth: 0
           path: pre-release
      - name: Get logseq-dev-theme files
        uses: actions/checkout@v3
        with:
           repository: pengx17/logseq-dev-theme
           fetch-depth: 0
           path: logseq-dev-theme
      - name: Install sass & compile css
        run: |
          cd logseq-dev-theme
          npm install -g sass
          sass --no-source-map --style compressed ./src/main.scss custom.css
      - name: Merge two css files
        run: cat pre-release/custom.css >> logseq-dev-theme/custom.css
      - name: Theme files
        run: |
          mkdir release && cd release
          cp ../pre-release/export.css ./
          cp ../logseq-dev-theme/custom.css ./
      - name: Upload Theme CSS
        uses: actions/upload-artifact@v3
        with:
          name: release-theme
          path: release

  release-package:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [merge-dev-theme]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load Fonts From Cache
        id: get-css-fonts
        uses: actions/cache@v3
        with: 
          path: ${{ env.FONTS_PATH }}
          key: ${{ runner.os }}-css-fonts
      - name: Download Theme files
        uses: actions/download-artifact@v3
        with:
          name: release-theme
          path: ${{ github.workspace }}
      - if: ${{ steps.get-css-fonts.outputs.cache-hit == 'true' }}
        run: mkdir fonts && cp ${{ env.FONTS_PATH }}/*.ttf fonts
      - name: zip themem css
        run: |
          if [ ! -d fonts ]; then mkdir fonts; fi
          version=`git tag --sort=-v:refname | head -n 1`
          zip -qq -r ${{ env.THEME_NAME }}-${version}.zip *.css package.json LICENSE fonts
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.THEME_NAME }}-*.zip
          draft: true
